"""The owner's source material never reaches the public tree, ROSE.md A.1.

static/img/brand/source/ holds the raster logo the mark was redrawn from, the
owner's style sheet, and a mockup of the home page generated by a neural net.
The mockup is why this is a contract and not housekeeping: it prints a 98% pass
rate, 10+ years, 1000+ graduates and categories A/A1/C/D, none of which are
true of this school, ROSE.md A.3. Served from our own domain under a guessable
name, that is a lie with our address on it.

static/img/source/ is the same idea for photographs, PHOTOS.md: the 2400px
originals the crops are cut from.
"""

from pathlib import Path

from django.conf import settings
from django.contrib.staticfiles import finders
from django.contrib.staticfiles.finders import get_finders

SOURCE_DIR = Path(settings.BASE_DIR) / "static" / "img" / "brand" / "source"

# ROSE.md A.1 names the first three; the fourth arrived with them.
EXPECTED_SOURCES = {
    "logo-light.png",
    "logo-dark.png",
    "mockup-home.png",
    "design-system.png",
}


def test_the_source_material_is_in_the_repository() -> None:
    """Whoever redraws the mark needs the original in front of them."""
    present = {p.name for p in SOURCE_DIR.iterdir() if p.is_file()}
    assert present >= EXPECTED_SOURCES, EXPECTED_SOURCES - present


def test_no_finder_lists_a_source_file() -> None:
    """collectstatic walks the finders, so this is what ships."""
    listed = [
        path
        for finder in get_finders()
        for path, _storage in finder.list([])
        if "source" in Path(path).parts
    ]
    assert listed == [], listed


def test_the_mockup_cannot_be_resolved_by_name() -> None:
    """The dev server and {% static %} go through find(), not list()."""
    for name in sorted(EXPECTED_SOURCES) + ["README.md"]:
        assert finders.find(f"img/brand/source/{name}") is None, name


def test_the_docker_image_does_not_carry_them() -> None:
    dockerignore = (Path(settings.BASE_DIR) / ".dockerignore").read_text(encoding="utf-8")
    assert "static/img/brand/source" in dockerignore
