# Generated by Django 5.1.15 on 2026-08-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('role_pl', models.CharField(blank=True, max_length=120, null=True)),
                ('role_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('role_uk', models.CharField(blank=True, max_length=120, null=True)),
                ('bio', models.TextField(blank=True)),
                ('bio_pl', models.TextField(blank=True, null=True)),
                ('bio_ru', models.TextField(blank=True, null=True)),
                ('bio_uk', models.TextField(blank=True, null=True)),
                ('since_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='people/')),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, limit_choices_to={'kind': 'license'}, related_name='instructors', to='courses.course')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gearbox', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], default='manual', max_length=8)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('note_pl', models.CharField(blank=True, max_length=200, null=True)),
                ('note_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('note_uk', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='vehicles/')),
                ('is_exam_spec', models.BooleanField(default=True, help_text='zgodny z wymogami egzaminacyjnymi')),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='courses.course')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
