# Generated by Django 5.1.15 on 2026-08-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=240)),
                ('question_pl', models.CharField(max_length=240, null=True)),
                ('question_ru', models.CharField(max_length=240, null=True)),
                ('question_uk', models.CharField(max_length=240, null=True)),
                ('answer', models.TextField()),
                ('answer_pl', models.TextField(null=True)),
                ('answer_ru', models.TextField(null=True)),
                ('answer_uk', models.TextField(null=True)),
                ('group', models.CharField(blank=True, max_length=40)),
                ('group_pl', models.CharField(blank=True, max_length=40, null=True)),
                ('group_ru', models.CharField(blank=True, max_length=40, null=True)),
                ('group_uk', models.CharField(blank=True, max_length=40, null=True)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('exam', 'Exam'), ('gov', 'Government'), ('tests', 'Tests'), ('local', 'Local')], db_index=True, max_length=8)),
                ('title', models.CharField(max_length=160)),
                ('title_pl', models.CharField(max_length=160, null=True)),
                ('title_ru', models.CharField(max_length=160, null=True)),
                ('title_uk', models.CharField(max_length=160, null=True)),
                ('description', models.CharField(max_length=240)),
                ('description_pl', models.CharField(max_length=240, null=True)),
                ('description_ru', models.CharField(max_length=240, null=True)),
                ('description_uk', models.CharField(max_length=240, null=True)),
                ('url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('group', 'order', 'id'),
            },
        ),
    ]
