# Generated by Django 5.1.15 on 2026-08-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_pl', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_uk', models.CharField(max_length=200, null=True)),
                ('lead', models.TextField(blank=True)),
                ('lead_pl', models.TextField(blank=True, null=True)),
                ('lead_ru', models.TextField(blank=True, null=True)),
                ('lead_uk', models.TextField(blank=True, null=True)),
                ('body', models.TextField()),
                ('body_pl', models.TextField(null=True)),
                ('body_ru', models.TextField(null=True)),
                ('body_uk', models.TextField(null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_title_pl', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_title_ru', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_title_uk', models.CharField(blank=True, max_length=70, null=True)),
                ('seo_desc', models.CharField(blank=True, max_length=170)),
                ('seo_desc_pl', models.CharField(blank=True, max_length=170, null=True)),
                ('seo_desc_ru', models.CharField(blank=True, max_length=170, null=True)),
                ('seo_desc_uk', models.CharField(blank=True, max_length=170, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(default='OSK Nawrocki', max_length=80)),
                ('street', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=80)),
                ('nip', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_primary', models.CharField(max_length=32)),
                ('phone_secondary', models.CharField(blank=True, max_length=32)),
                ('phone_tertiary', models.CharField(blank=True, max_length=32)),
                ('whatsapp', models.CharField(blank=True, max_length=32)),
                ('bank_account', models.CharField(blank=True, max_length=40)),
                ('bank_account_public', models.BooleanField(default=False)),
                ('founded_year', models.PositiveSmallIntegerField(default=1996)),
                ('map_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('map_lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('google_business_url', models.URLField(blank=True)),
                ('lead_notify_emails', models.CharField(help_text='comma separated', max_length=300)),
                ('analytics_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('office', 'Office'), ('psychology', 'Psychology lab')], max_length=16)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('opens', models.TimeField(blank=True, null=True)),
                ('closes', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('note_pl', models.CharField(blank=True, max_length=120, null=True)),
                ('note_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('note_uk', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name_plural': 'Opening hours',
                'ordering': ('department', 'weekday'),
                'unique_together': {('department', 'weekday')},
            },
        ),
    ]
