# Generated by Django 5.1.15 on 2026-09-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('title_pl', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_uk', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('description_pl', models.CharField(blank=True, max_length=300, null=True)),
                ('description_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('description_uk', models.CharField(blank=True, max_length=300, null=True)),
                ('file', models.FileField(blank=True, upload_to='documents/')),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PassRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('students', models.PositiveSmallIntegerField()),
                ('passed_1st', models.PositiveSmallIntegerField()),
                ('passed_2nd', models.PositiveSmallIntegerField(default=0)),
                ('passed_3rd', models.PositiveSmallIntegerField(default=0)),
                ('passed_4th', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('note_pl', models.CharField(blank=True, max_length=200, null=True)),
                ('note_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('note_uk', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pass rate',
                'verbose_name_plural': 'Pass rates',
                'ordering': ('-year',),
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_poster',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_poster_alt',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founded_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        # The default in 0001 still names the previous client this engine was
        # built for. That line is history and stays as it is — rewriting an
        # applied migration changes what an existing database was built from.
        # This is where the default becomes OSK Ostrycharz.
        migrations.AlterField(
            model_name='sitesettings',
            name='short_name',
            field=models.CharField(default='OSK Ostrycharz', max_length=80),
        ),
    ]
