# Generated by Django 5.1.15 on 2026-09-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pass_rates_downloads_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadfile',
            name='group',
            field=models.CharField(blank=True, help_text='Nagłówek nad plikiem. Puste — plik trafia do pierwszej grupy.', max_length=80, verbose_name='Grupa'),
        ),
    ]
