# Generated by Django 5.1.15 on 2026-09-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_downloadfile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadfile',
            name='group_pl',
            field=models.CharField(blank=True, help_text='Nagłówek nad plikiem. Puste — plik trafia do pierwszej grupy.', max_length=80, null=True, verbose_name='Grupa'),
        ),
        migrations.AddField(
            model_name='downloadfile',
            name='group_ru',
            field=models.CharField(blank=True, help_text='Nagłówek nad plikiem. Puste — plik trafia do pierwszej grupy.', max_length=80, null=True, verbose_name='Grupa'),
        ),
        migrations.AddField(
            model_name='downloadfile',
            name='group_uk',
            field=models.CharField(blank=True, help_text='Nagłówek nad plikiem. Puste — plik trafia do pierwszej grupy.', max_length=80, null=True, verbose_name='Grupa'),
        ),
    ]
