# Generated by Django 5.1.15 on 2026-09-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_downloadfile_group_pl_downloadfile_group_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassRateScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Okres')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Rok')),
                ('image', models.ImageField(upload_to='passrate/', verbose_name='Skan')),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pass rate scan',
                'verbose_name_plural': 'Pass rate scans',
                'ordering': ('-year', 'order', 'id'),
            },
        ),
    ]
