# Generated by Django 5.1.15 on 2026-09-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceitem',
            name='featured',
            field=models.BooleanField(default=False, help_text='Wyróżnia kartę w cenniku. Jedna w grupie.', verbose_name='Wyróżniony'),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='includes',
            field=models.TextField(blank=True, help_text='Po jednej pozycji w wierszu. Puste — karta pokaże samą cenę.', verbose_name='Co zawiera cena'),
        ),
    ]
