# Generated by Django 5.1.15 on 2026-09-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_priceitem_featured_priceitem_includes'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceitem',
            name='includes_pl',
            field=models.TextField(blank=True, help_text='Po jednej pozycji w wierszu. Puste — karta pokaże samą cenę.', null=True, verbose_name='Co zawiera cena'),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='includes_ru',
            field=models.TextField(blank=True, help_text='Po jednej pozycji w wierszu. Puste — karta pokaże samą cenę.', null=True, verbose_name='Co zawiera cena'),
        ),
        migrations.AddField(
            model_name='priceitem',
            name='includes_uk',
            field=models.TextField(blank=True, help_text='Po jednej pozycji w wierszu. Puste — karta pokaże samą cenę.', null=True, verbose_name='Co zawiera cena'),
        ),
    ]
