# Generated by Django 5.1.15 on 2026-08-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('title_pl', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_uk', models.CharField(max_length=200, null=True)),
                ('issuer', models.CharField(blank=True, max_length=160)),
                ('issuer_pl', models.CharField(blank=True, max_length=160, null=True)),
                ('issuer_ru', models.CharField(blank=True, max_length=160, null=True)),
                ('issuer_uk', models.CharField(blank=True, max_length=160, null=True)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_pl', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_uk', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('file', models.FileField(blank=True, upload_to='certificates/pdf/')),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('school', 'School'), ('vehicles', 'Vehicles'), ('yard', 'Yard'), ('events', 'Events')], db_index=True, max_length=10)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt', models.CharField(max_length=160)),
                ('alt_pl', models.CharField(max_length=160, null=True)),
                ('alt_ru', models.CharField(max_length=160, null=True)),
                ('alt_uk', models.CharField(max_length=160, null=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('caption_pl', models.CharField(blank=True, max_length=200, null=True)),
                ('caption_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('caption_uk', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
                ('legacy_name', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ('section', 'order', 'id'),
            },
        ),
    ]
