# Generated by Django 5.1.15 on 2026-08-25 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('text_pl', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('text_uk', models.TextField(null=True)),
                ('source', models.CharField(choices=[('google', 'Google'), ('manual', 'Manual'), ('facebook', 'Facebook')], default='manual', max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
